### ISSUE TITLE
Complete effectiveness rating

### ISSUE THREAD

**Issue by andyklimczak** [andyklimczak/TheReportOfTheWeek-API#1]
I started collecting effectiveness data on video 76 in the json file, so all videos prior need to be rechecked for effectiveness rating

**Comment by eugenern** [comment]
I will try to check the first 76 videos.

**Comment by andyklimczak** [comment]
@eugenern by effectiveness I meant effectiveness of the energy drinks, so only the energy drink reviews need to be checked. it's something he eventually stopped doing too

**Comment by eugenern** [comment]
I gotcha. Reviewbrah's descriptions of effectiveness can be pretty vague (for example "x, x+1 hours" or "up from x until y or y+1", as well as occasionally saying both but with contradictory figures), so I'm not always sure what to put.

**Comment by andyklimczak** [comment]
I think the value was the 'number of hours' it was effective for or something like that

**Comment by eugenern** [comment]
Right, it's just that Reviewbrah often gives effectiveness figures that aren't clearly one value, such as "4, 5 hours" and the like, in which case I'm not totally sure how to settle on a particular value but want to since Reviewbrah discussed it in the video.
